// <auto-generated />
namespace AuthorityManagement.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class db : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(db));
        
        string IMigrationMetadata.Id
        {
            get { return "201508100915283_db"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
