// <autogenerated>
//   This file was generated by T4 code generator RepositoryTextTemplate.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>


/**********************************************************************
*   该文档由T4模板自动生成，如需修改，请在同一命名空间下添加部分类
*
*
*
**********************************************************************/

using Apworks.Repositories;

using AuthorityManagement.Core.Domains;

namespace AuthorityManagement.Core.Repositories
{
	public partial interface IUserInGroupRepository:
					IRepository<UserInGroup> 
	{}

}
